gulp:
    build: ./gulp
    volumes:
        - "./data:/data"
node:
    build: ./node
    links:
        - influxdb
    volumes:
        - "./data:/data"
    ports:
        - "3000:3000"
influxdb:
    build: ./influxdb
    ports:
        - "8083:8083"
        - "8086:8086"
    volumes:
        - "./data/influxdb:/var/lib/influxdb"
opencpu:
    build: ./opencpu
    ports:
        - "8004:8004"
    links:
        - influxdb
apache:
    build: ./apache
    volumes:
        - "./data:/data"
    ports:
        - "80:80"
    links:
        - node
        - opencpu
        - influxdb
