gulp:
    build: ./gulp
    volumes:
        - "./data:/data"
node:
    build: ./node
    links:
        - mysql
    volumes:
        - "./data:/data"
    ports:
        - "3000:3000"
mysql:
    build: ./mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: "jactivity2"
    ports:
        - "3306:3306"
    volumes:
        - "./data/mysql:/var/lib/mysql"
opencpu:
    build: ./opencpu
    ports:
        - "8004:8004"
    links:
        - mysql
apache:
    build: ./apache
    volumes:
        - "./data:/data"
    ports:
        - "80:80"
    links:
        - node
        - opencpu

