node:
    build: ./node
    links:
        - mysql
    volumes:
        - "./data:/data"
    ports:
        - "8888:8888"
        - "3000:3000"
nginx:
    build: ./nginx
    links:
        - node
mysql:
    build: ./mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_DATABASE: jactivity2
    ports:
        - "3307:3306"
    volumes:
        - "./data/mysql:/var/lib/mysql"
opencpu:
    build: ./opencpu
    ports:
        - "8004:8004"
        - "80:80"
